services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=desafio_postgres;Port=5432;Database=desafio;Username=postgres;Password=admin
      - DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2UNENCRYPTEDSUPPORT=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      - DOTNET_CLI_TELEMETRY_OPTOUT=1

  postgres:
    image: "postgres:15"
    container_name: desafio_postgres
    hostname: desafio_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=desafio
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: